In [1]:
import numpy as np;
import pandas as pd;
from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv('input/train.csv')

In [3]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
data = np.array(data)

In [5]:
m,n  = data.shape
np.random.shuffle(data)
data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.
data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [6]:
def init_params():
  W1 = np.random.rand(10,784) - 0.5
  b1 = np.random.rand(10,1) - 0.5
  W2 = np.random.rand(10,10) - 0.5
  b2 = np.random.rand(10,1) - 0.5
  return W1,b1,W2,b2

In [7]:
def RelU(Z):
  return np.maximum(0,Z);

In [8]:
def softmax(Z):
  A = np.exp(Z) / sum(np.exp(Z))
  return A

In [9]:
def forward_prop(W1,b1,W2,b2,X):
  Z1=W1.dot(X) + b1
  A1=RelU(Z1)
  Z2= W2.dot(A1) + b2
  A2=softmax(Z2)
  return Z1, A1, Z2, A2

In [10]:
def one_hot(Y):
  one_hot_Y = np.zeros((Y.size, Y.max() + 1))
  one_hot_Y[np.arange(Y.size), Y] = 1
  one_hot_Y = one_hot_Y.T
  return one_hot_Y

In [11]:
def derivative_RelU(Z):
  return Z > 0 # slope is 1 for Z>0, and 0 for negative Z

In [18]:
def back_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
  one_hot_Y = one_hot(Y)
  dZ2 = A2 - one_hot_Y
  dW2 = 1 / m * dZ2.dot(A1.T)
  db2 = 1 / m * np.sum(dZ2)
  dZ1 = W2.T.dot(dZ2) * derivative_RelU(Z1)
  dW1 = 1 / m * dZ1.dot(X.T)
  db1 = 1 / m * np.sum(dZ1)
  return dW1, db1, dW2, db2

In [13]:
def update_params(W1,b1,W2,b2, dW1, db1, dW2, db2, alpha):
  W1= W1 -alpha * dW1;
  b1= b1 -alpha * db1;
  W2= W2 -alpha * dW2;
  b2= b2 -alpha * db2;
  return W1,b1, W2,b2 

In [14]:
def get_predictions(A2):
  return np.argmax(A2,0);

In [15]:
def get_accuracy(predictions,Y):
  print(predictions,Y)
  return np.sum(predictions == Y) / Y.size

In [30]:
def gradient_descent(X,Y, iterations,alpha):
  W1,b1,W2,b2 = init_params()
  for i in range(iterations):
    Z1,A1,Z2,A2 = forward_prop(W1,b1,W2,b2,X)
    dW1,db1,dW2,db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
    W1,b1,W2,b2 = update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha)
    if(i%50 == 0):
      print("Iteration:", i)
      print("Accuracy: ", get_accuracy(get_predictions(A2),Y))
  return W1,b1,W2,b2;

In [31]:
W1,b1,W2,b2 = gradient_descent(X_train,Y_train, 500, 0.1)

Iteration: 0
[1 1 8 ... 1 1 1] [5 9 8 ... 7 8 3]
Accuracy:  0.11870731707317073
Iteration: 50
[1 1 3 ... 2 9 2] [5 9 8 ... 7 8 3]
Accuracy:  0.40880487804878046
Iteration: 100
[1 4 3 ... 3 8 3] [5 9 8 ... 7 8 3]
Accuracy:  0.5617804878048781
Iteration: 150
[9 4 3 ... 3 8 3] [5 9 8 ... 7 8 3]
Accuracy:  0.6427560975609756
Iteration: 200
[9 4 3 ... 3 8 3] [5 9 8 ... 7 8 3]
Accuracy:  0.7007560975609756
Iteration: 250
[5 4 0 ... 3 8 3] [5 9 8 ... 7 8 3]
Accuracy:  0.7456341463414634
Iteration: 300
[5 4 0 ... 7 8 3] [5 9 8 ... 7 8 3]
Accuracy:  0.7784146341463415
Iteration: 350
[5 9 0 ... 7 8 3] [5 9 8 ... 7 8 3]
Accuracy:  0.8010487804878049
Iteration: 400
[5 9 0 ... 7 8 3] [5 9 8 ... 7 8 3]
Accuracy:  0.8173170731707317
Iteration: 450
[5 9 0 ... 7 8 3] [5 9 8 ... 7 8 3]
Accuracy:  0.8292926829268292
